### ISSUE TITLE
rvierdiiev - lack of input validation in OptionsConfig

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2022-11-buffer-judging#11]
rvierdiiev

medium

# lack of input validation in OptionsConfig

## Summary
OptionsConfig doesn't validate some provided variable which can lead to incorrect work of protocol
## Vulnerability Detail
Both `setMaxPeriod` and `setMinPeriod` functions is OptionsConfig [do not check](https://github.com/sherlock-audit/2022-11-buffer/blob/main/contracts/contracts/core/OptionsConfig.sol#L67-L83) that after variable is set `OptionsConfig.maxPeriod >= OptionsConfig.minPeriod`.
In case if incorrect values are set then no trader will be possible to initiate new trade, because of [check](https://github.com/sherlock-audit/2022-11-buffer/blob/main/contracts/contracts/core/BufferBinaryOptions.sol#L282-L283) in BufferBinaryOptions contract.

Both OptionsConfig.setAssetUtilizationLimit and setOverallPoolUtilizationLimit [doesn't check](https://github.com/sherlock-audit/2022-11-buffer/blob/main/contracts/contracts/core/OptionsConfig.sol#L55-L65) the value to be greater than 0.
Because of that BufferBinaryOptions.getMaxUtilization function will [revert](https://github.com/sherlock-audit/2022-11-buffer/blob/main/contracts/contracts/core/BufferBinaryOptions.sol#L290-L312) and it will not be possible to create new option.
## Impact
Not possible to initiate new trades and create option.
## Code Snippet
https://github.com/sherlock-audit/2022-11-buffer/blob/main/contracts/contracts/core/OptionsConfig.sol#L67-L83
https://github.com/sherlock-audit/2022-11-buffer/blob/main/contracts/contracts/core/OptionsConfig.sol#L55-L65
## Tool used

Manual Review

## Recommendation
Check that OptionsConfig.maxPeriod >= OptionsConfig.minPeriod after variable set. Check that `overallPoolUtilizationLimit ` and `assetUtilizationLimit` are greater than 0.

**Comment by 0x00052** [comment]
Fixed in [PR#6](https://github.com/bufferfinance/Buffer-Protocol-v2/pull/6)

Changes look good. Various admin setters validate inputs
