### ISSUE TITLE
cccz - When tokenX is an ERC777 token, users can bypass maxLiquidity

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2022-11-buffer-judging#112]
cccz

medium

# When tokenX is an ERC777 token, users can bypass maxLiquidity

## Summary
When tokenX is an ERC777 token, users can use callbacks to provide liquidity exceeding maxLiquidity
## Vulnerability Detail
In BufferBinaryPool._provide, when tokenX is an ERC777 token, the tokensToSend function of account will be called in tokenX.transferFrom before sending tokens. When the user calls provide again in tokensToSend, since BufferBinaryPool has not received tokens at this time, totalTokenXBalance() has not increased, and the following checks can be bypassed, so that users can provide liquidity exceeding maxLiquidity.
```solidity
         require(
             balance + tokenXAmount <= maxLiquidity,
             "Pool has already reached it's max limit"
         );
```
## Impact
users can provide liquidity exceeding maxLiquidity.

## Code Snippet
https://github.com/sherlock-audit/2022-11-buffer/blob/main/contracts/contracts/core/BufferBinaryPool.sol#L216-L240
## Tool used

Manual Review

## Recommendation
Change to
```diff
    function _provide(
        uint256 tokenXAmount,
        uint256 minMint,
        address account
    ) internal returns (uint256 mint) {
+        bool success = tokenX.transferFrom(
+            account,
+            address(this),
+            tokenXAmount
+        );
        uint256 supply = totalSupply();
        uint256 balance = totalTokenXBalance();

        require(
            balance + tokenXAmount <= maxLiquidity,
            "Pool has already reached it's max limit"
        );

        if (supply > 0 && balance > 0)
            mint = (tokenXAmount * supply) / (balance);
        else mint = tokenXAmount * INITIAL_RATE;

        require(mint >= minMint, "Pool: Mint limit is too large");
        require(mint > 0, "Pool: Amount is too small");

-        bool success = tokenX.transferFrom(
-            account,
-            address(this),
-            tokenXAmount
-        );
```

**Comment by 0x00052** [comment]
Escalate for 10 USDC

This should be low for a few reasons:

1) It would require that admin has to create a market with tokenX as an ERC777 which is extremely niche.

2) Protocol is deployed on Arbitrum, so even tokens that are ERC777 on mainnet will be standard ERC20s after using Arbitrum bridge. This even further narrows down the number of tokens that could be used.

3) There is no danger in exceeding the deposit cap, as it is a soft cap. The deposit cap can be surpassed legitimately by premium added to the pool and pool will function completely as normal.

Overall a clever idea but application is too niche and there is zero danger to exceeding the soft deposit cap.

**Comment by hrishibhat** [comment]
Escalation accepted

Considering this to be an edge case, There doesn't seem to be a significant impact of bypassing the maxLiquidity.
