### ISSUE TITLE
KingNFT - A suspicious keeper can set 'nextQueueIdToProcess' state variable to any value

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2022-11-buffer-judging#34]
KingNFT

medium

# A suspicious keeper can set 'nextQueueIdToProcess' state variable to any value

## Summary
There is no  security check before changing 'nextQueueIdToProcess'  state variable. A suspicious keeper can set it to any value, programs of other keepers working based the variable might be stuck.

## Vulnerability Detail
A brief overview of 'resolveQueuedTrades()' function and the vulnerability.
```solidity
function resolveQueuedTrades(OpenTradeParams[] calldata params) external {
    _validateKeeper();
    for (uint32 index = 0; index < params.length; index++) {
        OpenTradeParams memory currentParams = params[index];
        QueuedTrade memory queuedTrade = queuedTrades[
            currentParams.queueId
        ];
        //...
        if (
            !queuedTrade.isQueued ||
            currentParams.timestamp != queuedTrade.queuedTime
        ) {
            // @audit continue rather than revert while encountering invalid trade
            continue;
        }

        // ...
    }

    // @audit take queueId from last array item, it could be any value
    nextQueueIdToProcess = params[params.length - 1].queueId + 1;
}
```

## Impact
The logic of keeper program working based on 'nextQueueIdToProcess' might look like this
```solidity
while (true) {
    nextId = router.nextQueueIdToProcess();
    queuedTrade = router.queuedTrades(nextId);
    if (queuedTrade.user != 0) {
        // get queued trades, collect signatures from publisher, submit data to chain and get reward
    } else {
        sleepForAWhile();
    }
}
```

A suspicious keeper can break the above program by always appending an invalid trade after valid trades.

## Code Snippet
https://github.com/sherlock-audit/2022-11-buffer/blob/main/contracts/contracts/core/BufferRouter.sol#L184

## Tool used

Manual Review

## Recommendation
```solidity
function resolveQueuedTrades(OpenTradeParams[] calldata params) external {
    // ...
    require(params[params.length - 1].user != address(0), "invalid params"); // @fix  check before changing
    if (params[params.length - 1].queueId + 1 > nextQueueIdToProcess) { // @fix  ensure increasing only
        nextQueueIdToProcess = params[params.length - 1].queueId + 1;
    }
}
```
Duplicate of #63

**Comment by 0x00052** [comment]
Fixed in [PR#12](https://github.com/bufferfinance/Buffer-Protocol-v2/pull/12)

Changes look good. userNextQueueIndexToProcess and nextQueueIdToProcess were no longer being utilized so they have been removed
