### ISSUE TITLE
8olidity - `BufferBinaryPool::send()`unlocks the total number of tokenx of the user

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2022-11-buffer-judging#42]
8olidity

high

# `BufferBinaryPool::send()`unlocks the total number of tokenx of the user

## Summary
`BufferBinaryPool::send()`unlocks the total number of tokenx of the user
## Vulnerability Detail

The number of tokenX of `tokenXAmount` will be sent to the to address in `BufferBinaryPool::send()`. But what `lockedAmount` subtracts here is not the number of `tokenXAmount`. Instead, it is all the number of previous users `lock()`. All tokenx previously locked by the user will be unlocked.

For example, if the number of lock is 10, then the tokenXAmount is 10.
```solidity
        lockedLiquidity[msg.sender].push(
            LockedLiquidity(tokenXAmount, premium, true)
        );
```

Then the user calls `send (id,to,0) `and the number of `tokenXAmount` is 0. But the function unlocks all the previous tokenx of the user.
```solidity
        ll.locked = false;
        lockedPremium = lockedPremium - ll.premium;
        lockedAmount = lockedAmount - ll.amount; // @audit 
```

## Impact
`BufferBinaryPool::send()`unlocks the total number of tokenx of the user
## Code Snippet
https://github.com/sherlock-audit/2022-11-buffer/blob/main/contracts/contracts/core/BufferBinaryPool.sol#L198
## Tool used

Manual Review

## Recommendation
```solidity
    function send(
        uint256 id,
        address to,
        uint256 tokenXAmount
    ) external override onlyRole(OPTION_ISSUER_ROLE) {
        LockedLiquidity storage ll = lockedLiquidity[msg.sender][id];
        require(ll.locked, "Pool: lockedAmount is already unlocked");
        require(to != address(0));

       

        uint256 transferTokenXAmount = tokenXAmount > ll.amount 
            ? ll.amount
            : tokenXAmount;

        ll.locked = false;
        lockedPremium = lockedPremium - ll.premium;
        lockedAmount = lockedAmount - transferTokenXAmount;

        bool success = tokenX.transfer(to, transferTokenXAmount);
        require(success, "Pool: The Payout transfer didn't go through");

        if (transferTokenXAmount <= ll.premium)
            emit Profit(id, ll.premium - transferTokenXAmount);
        else emit Loss(id, transferTokenXAmount - ll.premium);
    }
```

**Comment by 9olidity** [comment]
Escalate for 1 USDC.
The source of `ll.amount` in `bufferbingarypool.sol` is `lockedLiquidity[msg.sender][id]`, which can be called by `BufferBinaryoptions.sol`, where `tokenXAmount` corresponds to `option.lockedAmount`, If the user has multiple optionids, these two values will not be equal


```solidity
    function _exercise(uint256 optionID, uint256 priceAtExpiration)
        internal
        returns (uint256 profit)
    {
        Option storage option = options[optionID];
        address user = ownerOf(optionID);
        profit = option.lockedAmount;
        pool.send(optionID, user, profit);

        // Burn the option
        _burn(optionID);
        option.state = State.Exercised;
        emit Exercise(user, optionID, profit, priceAtExpiration);
    }


    function send(
        uint256 id,
        address to,
        uint256 tokenXAmount
    ) external override onlyRole(OPTION_ISSUER_ROLE) {
        LockedLiquidity storage ll = lockedLiquidity[msg.sender][id];
        require(ll.locked, "Pool: lockedAmount is already unlocked");
```

**Comment by hrishibhat** [comment]
Escalation rejected 

`ll.amount` is the amount pushed into `lockedLiquidity` array every time BufferCallOptions locks the funds for every option ID. 
`option.lockedAmount` is obtained from a respective optionId using `options[optionID]`. As mentioned in the comment above, send is an access-controlled function.
