### ISSUE TITLE
0x4non - Due lack of validation the `maxLiquidity` could be set in an invalid amount

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2022-11-buffer-judging#50]
0x4non

medium

# Due lack of validation the `maxLiquidity` could be set in an invalid amount

## Summary
There is no check in set `setMaxLiquidity` function

## Vulnerability Detail
This invariant should always hold `maxLiquidity >= totalTokenXBalance()` and because there is no check in `maxLiquidity` it could be break.

## Impact
The `maxLiquidity` could be set in an invalid amount

## Code Snippet
https://github.com/sherlock-audit/2022-11-buffer/blob/main/contracts/contracts/core/BufferBinaryPool.sol#L63
```solidity
    /**
     * @notice Used for adjusting the max limit of the pool
     */
    function setMaxLiquidity(uint256 _maxLiquidity)
        external
        onlyRole(DEFAULT_ADMIN_ROLE)
    {
        maxLiquidity = _maxLiquidity;
        emit UpdateMaxLiquidity(_maxLiquidity);
    }
```

## Tool used
Manual Review

## Recommendation
Add a require to ensure the new `_maxLiquidity` value is valid;

```diff
diff --git a/contracts/contracts/core/BufferBinaryPool.sol b/contracts/contracts/core/BufferBinaryPool.sol
index ea4a276..a26a8b9 100644
--- a/contracts/contracts/core/BufferBinaryPool.sol
+++ b/contracts/contracts/core/BufferBinaryPool.sol
@@ -60,6 +60,7 @@ contract BufferBinaryPool is
         external
         onlyRole(DEFAULT_ADMIN_ROLE)
     {
+        require(_maxLiquidity >= totalTokenXBalance(), 'Invalid new maxLiquidity');
         maxLiquidity = _maxLiquidity;
         emit UpdateMaxLiquidity(_maxLiquidity);
     }
```

**Comment by 0x00052** [comment]
Fixed in [PR#16](https://github.com/bufferfinance/Buffer-Protocol-v2/pull/16)

Changes look good. maxLiquidity can no longer be set below the current amount of liquidity in the pool.
