### ISSUE TITLE
peanuts - Transfer of premium funds is not called correctly

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2022-11-buffer-judging#58]
peanuts

medium

# Transfer of premium funds is not called correctly

## Summary

Transfer of premium funds is not called correctly which may lead to function revert.

## Vulnerability Detail

When a user creates a trade, funds are first deposited into the BufferRouter and then transferred from BufferRouter to the targetContract, which is an instance of BufferBinaryOption.

        tokenX.transfer(queuedTrade.targetContract, revisedFee);

Afterwards, createFromRouter is called which calls pool.lock()

        pool.lock(optionID, option.lockedAmount, option.premium);

In BufferBinaryPool where the function lock exists, the premium is transferred from the msg.sender to address(this)

        @notice Called by BufferCallOptions to lock the funds
      
        bool success = tokenX.transferFrom(msg.sender, address(this), premium);

The lock function can be called through createRouter() which has `onlyRole(ROUTER_ROLE)` or directly by the `onlyRole(OPTION_ISSUER_ROLE)`, so msg.sender points to either of these 2 contract addresses. Since the funds is in BufferBinaryOption and not BufferRouter nor BufferCallOptions, either contract has to supply the funds for the function to succeed. The problem lies when BufferRouter or BufferCallOptions does not have funds in the contract to guarantee that the lock function will succeed, thereby creating confusion and potential griefing.  

## Impact

Function succeeds haphazardly. 

## Code Snippet

https://github.com/sherlock-audit/2022-11-buffer/blob/main/contracts/contracts/core/BufferRouter.sol#L331

https://github.com/sherlock-audit/2022-11-buffer/blob/main/contracts/contracts/core/BufferBinaryOptions.sol#L142

https://github.com/sherlock-audit/2022-11-buffer/blob/main/contracts/contracts/core/BufferBinaryPool.sol#L161

## Tool used

Manual Review

## Recommendation

Either leave the funds that the user transferred in the BufferRouter and settle the transfer of settlement fee there, or point to the BufferBinaryOption when transferring.

**Comment by 0x00052** [comment]
Fixed in [PR#19](https://github.com/bufferfinance/Buffer-Protocol-v2/pull/19)

Typo in comment fixed
