### ISSUE TITLE
koxuan - tier in setReferrerTier can be set to out of bound, causing referrer to not receive any referrerFee

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2022-11-buffer-judging#65]
koxuan

medium

# tier in setReferrerTier can be set to out of bound, causing referrer to not receive any referrerFee

## Summary
There is no checks on tier and therefore, it can be set mistakenly to an out of bound value, causing referrer to receive 0 for referrer fees.  
## Vulnerability Detail
Tier can be set to > 3, which is not set in referralTierDiscount mapping and therefore will always return 0.

```solidity
    function setReferrerTier(address _referrer, uint8 tier)
        external
        override
        onlyOwner
    {
        referrerTier[_referrer] = tier;
        emit UpdateReferrerTier(_referrer, tier);
    }
```
## Impact
Referral will receive 0 for referral fees due to admin mistakenly setting tier to an out of bound value.

## Code Snippet

[ReferralStorage.sol#L46-L53](https://github.com/sherlock-audit/2022-11-buffer/blob/main/contracts/contracts/core/ReferralStorage.sol#L46-L53)

## Tool used

Manual Review

## Recommendation
Since number of tiers is hardcoded to 3 in `configure`, we can safely do a check of `require(tier < 3)`

**Comment by 0x00052** [comment]
Fixed in [PR#25](https://github.com/bufferfinance/Buffer-Protocol-v2/pull/25)

Changes look good. Added input validation for setReferrerTier
