### ISSUE TITLE
silviaxyz - Creation window won't work always.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2022-11-buffer-judging#79]
silviaxyz

high

# Creation window won't work always.

## Summary
For some cases like holidays, forex markets are closed. 

## Vulnerability Detail
In tests it was tested for timestamp but in the code it is block.timestamp. Also, for non existent records it will retun 0 from config.marketTimes function which does not have validation. For day switches it causes wrong calculations. Also, 

## Impact
Even if we would be in creationWindow for forex options it will still pass the isInCreationWindow check. 

## Code Snippet
https://github.com/sherlock-audit/2022-11-buffer/blob/main/contracts/contracts/core/BufferBinaryOptions.sol#L240-L270

## Tool used

Manual Review

## Recommendation
Update test according to timestamp and use timestamp in the code.

**Comment by gguney** [comment]
Escalate for 2 USDC
It is accepted but there is no reward for this accepted issue there is even PR for the issue from the sponsor.

**Comment by hrishibhat** [comment]
Escalation rejected

Sponsor confirmed does not mean the issue is a medium. 
Forgetting to toggle creations by a trusted admin cannot be considered as a valid medium.
