### ISSUE TITLE
0x52 - Early depositors to BufferBinaryPool can manipulate exchange rates to steal funds from later depositors

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2022-11-buffer-judging#81]
0x52

medium

# Early depositors to BufferBinaryPool can manipulate exchange rates to steal funds from later depositors

## Summary

To calculate the exchange rate for shares in BufferBinaryPool it divides the total supply of shares by the totalTokenXBalance of the vault. The first deposit can mint a very small number of shares then donate tokenX to the vault to grossly manipulate the share price. When later depositor deposit into the vault they will lose value due to precision loss and the adversary will profit.

## Vulnerability Detail

    function totalTokenXBalance()
        public
        view
        override
        returns (uint256 balance)
    {
        return tokenX.balanceOf(address(this)) - lockedPremium;
    }

Share exchange rate is calculated using the total supply of shares and the totalTokenXBalance, which leaves it vulnerable to exchange rate manipulation. As an example, assume tokenX == USDC. An adversary can mint a single share, then donate 1e8 USDC. Minting the first share established a 1:1 ratio but then donating 1e8 changed the ratio to 1:1e8. Now any deposit lower than 1e8 (100 USDC) will suffer from precision loss and the attackers share will benefit from it.

## Impact

Adversary can effectively steal funds from later users through precision loss

## Code Snippet

https://github.com/sherlock-audit/2022-11-buffer/blob/main/contracts/contracts/core/BufferBinaryPool.sol#L405-L412

## Tool used

Manual Review

## Recommendation

Require a small minimum deposit (i.e. 1e6)

**Comment by pauliax** [comment]
Escalate for 30 USDC.

I believe this issue should be at most the Medium but probably Low severity because:
this kind of issue recently became very popular and well-known so participants often submit it with very little context and understanding. Usually, it is valid when the minting is simple but in this case, the protocol has some efforts to combat such a situation. The function ```_provide``` has a slippage control parameter named ```minMint``` so any external caller can set in advance the minimum amount of shares that satisfy them to prevent such frontrunning:
```solidity
    /**
     * @param minMint Minimum amount of tokens that should be received by a provider.
                      Calling the provide function will require the minimum amount of tokens to be minted.
                      The actual amount that will be minted could vary but can only be higher (not lower) than the minimum value.
    */
```
```solidity
        if (supply > 0 && balance > 0)
            mint = (tokenXAmount * supply) / (balance);
        else mint = tokenXAmount * INITIAL_RATE;

        require(mint >= minMint, "Pool: Mint limit is too large");
        require(mint > 0, "Pool: Amount is too small");
```

**Comment by hrishibhat** [comment]
Escalation accepted

While this could happen only during the first deposit, with minimal loss of funds, the admin can block all deposits and then deploy another instance with a small deposit to prevent the attack from happening again.
