### ISSUE TITLE
HonorLt - Signature validation params

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2022-11-buffer-judging#88]
HonorLt

high

# Signature validation params

## Summary
When validating the signature it does not check all the corresponding parameters leaving a gap to substitute with malicious values.

## Vulnerability Detail
Functions ```resolveQueuedTrades``` and ```unlockOptions``` rely on valid publisher signatures. It validates the timestamp, asset, and price but fails to check the corresponding ```queueId``` or ```optionId```.
For example, here it does not check that the signer has signed for this particular ```queueId```:
```solidity
            OpenTradeParams memory currentParams = params[index];
            QueuedTrade memory queuedTrade = queuedTrades[
                currentParams.queueId
            ];
            bool isSignerVerifed = _validateSigner(
                currentParams.timestamp,
                currentParams.asset,
                currentParams.price,
                currentParams.signature
            );
            // Silently fail if the signature doesn't match
            if (!isSignerVerifed) {
                emit FailResolve(
                    currentParams.queueId,
                    "Router: Signature didn't match"
                );
                continue;
            }
```
Similarly, here the ```optionId``` is not checked:
```solidity
            CloseTradeParams memory params = optionData[i];
            IBufferBinaryOptions optionsContract = IBufferBinaryOptions(
                params.asset
            );
            (, , , , , uint256 expiration, , , ) = optionsContract.options(
                params.optionId
            );

            bool isSignerVerifed = _validateSigner(
                params.expiryTimestamp,
                params.asset,
                params.priceAtExpiry,
                params.signature
            );

            // Silently fail if the timestamp of the signature is wrong
            if (expiration != params.expiryTimestamp) {
                emit FailUnlock(params.optionId, "Router: Wrong price");
                continue;
            }

            // Silently fail if the signature doesn't match
            if (!isSignerVerifed) {
                emit FailUnlock(
                    params.optionId,
                    "Router: Signature didn't match"
                );
                continue;
            }
```

## Impact
The keeper can choose any queued trade even when the assets do not match. Also, can unlock any option id with ```priceAtExpiry``` that was not meant for this option. What's more, the same signature can be re-used for trades/options with similar data. 
While these functions are in the keeper zone, when ```isInPrivateKeeperMode``` is disabled, anyone can call it.

## Code Snippet

https://github.com/bufferfinance/Buffer-Protocol-v2/blob/master/contracts/core/BufferRouter.sol#L133-L185

https://github.com/bufferfinance/Buffer-Protocol-v2/blob/master/contracts/core/BufferRouter.sol#L187-L232

https://github.com/bufferfinance/Buffer-Protocol-v2/blob/master/contracts/core/BufferRouter.sol#L260-L295

## Tool used

Manual Review

## Recommendation
```_validateSigner``` should also include ```queueId```/```optionId```.

Duplicate of #86

**Comment by pauliax** [comment]
Escalate for 10 USDC.

This is practically the same as #85. I quote the impact:
"The keeper can choose any queued trade even when the assets do not match".
Also, before submitting this I got the confirmation from the sponsor:
![image](https://user-images.githubusercontent.com/22328890/205389754-e62386d0-8c1a-49f6-999e-ae15a3a40806.png)

**Comment by hrishibhat** [comment]
Escalation rejected

The issue mainly talks about queueId/optionId and the explanation is incorrect including the unlockOptions issue.
