### ISSUE TITLE
rvierdiiev - Possible trade ignore from keepers

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2022-11-buffer-judging#9]
rvierdiiev

high

# Possible trade ignore from keepers

## Summary
When user won option then the only option for him to get money is any keeper to call `BufferRouter.unlockOptions`. If any keeper didn't call `unlockOptions` for option then user doen't have any ability to do that himself. As result he can't withdraw the funds he won.
## Vulnerability Detail
BufferRouter.resolveQueuedTrades is the only function that allows to resolve options. And it's callable only [by keepers](https://github.com/sherlock-audit/2022-11-buffer/blob/main/contracts/contracts/core/BufferRouter.sol#L137). If for some reasons keepers will not call resolveQueuedTrades function for option then user doesn't have any ability to resolve option himself. As result he will not be able to get his funds.
## Impact
Users funds are stucked until any keeper will call resolveQueuedTrades for him.
## Code Snippet
https://github.com/sherlock-audit/2022-11-buffer/blob/main/contracts/contracts/core/BufferRouter.sol#L136-L185
## Tool used

Manual Review

## Recommendation
Add function that users can call to resolve option themselves. They will also provide data from publisher and option id.

**Comment by rvierdiyev** [comment]
Escalate for 1 USDC.
This is separate issue and not a duplicate of [2](https://github.com/sherlock-audit/2022-11-buffer-judging/issues/2).
It states that after user won his option, keepers can not call resolveQueuedTrades(ignore user) and as result user will not be able to receive his payment. Separate function should be added.
This is high severity issue.

**Comment by hrishibhat** [comment]
Escalation rejected

It is not marked a duplicate of #2 anymore

Also, the private keepers are trusted entities there is no reason to not resolve trades, additionally, the admin can set `isInPrivateKeeperMode` to false, and anyone can call `resolveQueuedTrades`.
