### ISSUE TITLE
HonorLt - Support of various tokens

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2022-11-buffer-judging#90]
HonorLt

medium

# Support of various tokens

## Vulnerability Detail
The protocol intends to handle any ERC20 as per sponsor's comment:
_The system is made to handle any token. Initially we'll be starting with USDC and BFR(Our token), later on we may add more._

There exist a lot of variations of ERC20s that do not behave as expected: https://github.com/xwvvvvwx/weird-erc20
The protocol fails to account for this in various cases. For example, almost every function check the return value:
```solidity
        bool success = tokenX.transferFrom(msg.sender, address(this), premium);
        require(success, "Pool: The Premium transfer didn't go through");
```
However, here it does not validate it:
```solidity
      // Transfer the fee specified from the user to this contract.
      // User has to approve first inorder to execute this function
      IERC20(optionsContract.tokenX()).transferFrom(
            msg.sender,
            address(this),
            totalFee
        );
```
```solidity
        // Refund the user in case the trade amount was lesser
        if (revisedFee < queuedTrade.totalFee) {
            tokenX.transfer(
                queuedTrade.user,
                queuedTrade.totalFee - revisedFee
            );
        }
```
```solidity
  tokenX.transfer(config.settlementFeeDisbursalContract(), settlementFee);
```
Also, it just checks the return value but a more robust approach is to compare the balance before/after and validate that exactly this amount was actually transferred.

Another problem might arise with tokens that contain callback hooks (e.g. ERC777). Here, for example, the protocol first transfers the tokens and only then mints the shares: 
```solidity
        bool success = tokenX.transferFrom(
            account,
            address(this),
            tokenXAmount
        );
        require(success, "Pool: The Provide transfer didn't go through");

        _mint(account, mint);
```

One more small issue is with approvals:
```solidity
    function approvePoolToTransferTokenX() public {
        tokenX.approve(address(pool), ~uint256(0));
    }
```
Some tokens require first setting the approval to 0 before setting the new value. For example, Tether:
_To change the approve amount you first have to reduce the addresses allowance to 0 calling
approve(spender, 0)._

## Impact
The current version of the protocol is not robust enough to handle different tokens.

## Code Snippet

https://github.com/bufferfinance/Buffer-Protocol-v2/blob/master/contracts/core/BufferRouter.sol#L84-L90

https://github.com/bufferfinance/Buffer-Protocol-v2/blob/master/contracts/core/BufferBinaryPool.sol#L236-L243

https://github.com/bufferfinance/Buffer-Protocol-v2/blob/master/contracts/core/BufferBinaryOptions.sol#L84-L89

https://github.com/bufferfinance/Buffer-Protocol-v2/blob/master/contracts/core/BufferRouter.sol#L333-L339

https://github.com/bufferfinance/Buffer-Protocol-v2/blob/master/contracts/core/BufferBinaryOptions.sol#L141

## Tool used

Manual Review

## Recommendation
Consider using ```SafeERC20``` library for token transfers and validating balance before/after.

Duplicate of #73

**Comment by 0x00052** [comment]
Escalate for 7 USDC

Dupe of 73, 76 and 112. Discusses safeTransfer for tokens that don't revert on failed trasnfers. Discusses supporting fee on trasnfer with balance checks. It also discusses the reetrancy issues for ERC777 in BufferBinaryPool#_provide. Should be counted as duplicate of all three, since it discusses the issues present in all three issue.

**Comment by hrishibhat** [comment]
Escalation rejected

Can only consider as a duplicate of one issue
