### ISSUE TITLE
0xadrii - ERC20 `transferFrom` return values not checked

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2022-11-buffer-judging#92]
0xadrii

low

# ERC20 `transferFrom` return values not checked

## Summary
ERC20 `transferFrom` return values are not checked, leading to potential issues. 
## Vulnerability Detail
The transferFrom() function returns a boolean value indicating success. This parameter needs to be checked to see if the transfer has been successful. 

Some tokens like [ZRX](https://etherscan.io/token/0xe41d2489571d322189246dafa5ebde1f4699f498#code) will not revert if the transfer failed but return false instead. Tokens that don't actually perform the transfer and return false are still counted as a correct transfer. Also, some tokens like [USDT](https://etherscan.io/token/0xdac17f958d2ee523a2206206994597c13d831ec7) don't even return a boolean nor revert, so just trying to check on the boolean would make the whole transaction revert.

As stated in discord channel by the Buffer team, although they'll be starting with USDC and BFR (their token), they might add support for more tokens in the future.

## Impact
Raising as LOW as it currently does not impact the protocol due to the tokens accepted, but might lead to funds loss if some tokens like the ones mentioned above are introduced to it.

## Code Snippet
https://github.com/sherlock-audit/2022-11-buffer/blob/main/contracts/contracts/core/BufferRouter.sol#L86
```solidity
function initiateTrade(
        uint256 totalFee,
        uint256 period,
        bool isAbove,
        address targetContract,
        uint256 expectedStrike,
        uint256 slippage,
        bool allowPartialFill,
        string memory referralCode,
        uint256 traderNFTId
    ) external returns (uint256 queueId) {
        ...
        // Transfer the fee specified from the user to this contract.
        // User has to approve first inorder to execute this function
        // @audit this will cause issues if tokenX does not revert on failure, or if it does not even return any feedback boolean 
        //(like USDT)
        IERC20(optionsContract.tokenX()).transferFrom(
            msg.sender,
            address(this),
            totalFee
        );
        ...
    }

```
## Tool used

Manual Review

## Recommendation
I recommend using [OpenZeppelin's SafeERC20](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/utils/SafeERC20.sol#L22) version with the safeTransfer function that handles the return value check as well as non-standard-compliant tokens.

Duplicate of #73

**Comment by 0x00052** [comment]
Escalate for 6 USDC

Clear dupe of #73, probably missed because it watson submitted as low

**Comment by hrishibhat** [comment]
Escalation accepted
