### ISSUE TITLE
Bnke0x0 - Support of different ERC20 tokens

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2022-11-buffer-judging#94]
Bnke0x0

medium

# Support of different ERC20 tokens

## Impact
The current version of the codebase does not handle special cases of tokens, e.g. deflationary, rebasing, or those that return true/false on success (see: https://github.com/d-xo/weird-erc20). Function purchase transfers tokens from msg.sender but it does not check the return value, nor how many tokens were actually transferred

## Code Snippet
https://github.com/sherlock-audit/2022-11-buffer/blob/main/contracts/contracts/core/BufferBinaryPool.sol#L161

                       'tokenX.transferFrom(msg.sender, address(this), premium);'
## Tool used

Manual Review

## Recommendation

I have 2 suggestions here:

1. Use SafeERC20 library to handle token transfers: [https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/utils/SafeERC20.sol](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/utils/SafeERC20.sol)
2. Consider checking the actual balances transferred (balance after-before) or clearly documenting that you do not support deflationary / rebasing / etc tokens.

Duplicate of #76

**Comment by 0x00052** [comment]
Escalate for 6 USDC

Discussion and recommendations makes it a dupe of both #73 and #76. Watson already has a dupe of #73 so this should be counted as a dupe of #76.
